services:
  - type: web
    name: mindbloom-backend
    env: python
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python -m uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHONPATH
        value: "."
      - key: MONGO_URL
        sync: false
      - key: DB_NAME
        value: "mindbloom"
      - key: PYTHON_VERSION
        value: "3.11"
      - key: SECRET_KEY
        generateValue: true
